### ISSUE TITLE
Error deleting a record from results grid 

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#439]
I have this error when I try to delete giving click in the red x from grid
![image](https://user-images.githubusercontent.com/36895220/37982634-b62a0b4c-31b6-11e8-8015-d03bb476b410.png)
 this is the error
![image](https://user-images.githubusercontent.com/36895220/37982476-459fbef8-31b6-11e8-8752-bffb7ef0a8ec.png)

**Comment by erdusa** [comment]
Hi @wind39, please don't forget this issue

**Comment by wind39** [comment]
Hi @erdusa ,

We will try and tackle this issue for next release, 2.12.0.

Regards,

William Ivanski

**Comment by wind39** [comment]
I managed to write a simple test case:

```
>> create table test (
  dt timestamp without time zone primary key,
  msg text
);
CREATE TABLE
>> insert into test values (now(), 'This is a test')
INSERT 0 1
```

Then go to Edit Data on table `test` and try to remove the row by clicking on the red X and click on `Save Changes`. It will throw the following error:

![image](https://user-images.githubusercontent.com/7719686/53097832-1da36e00-3501-11e9-85b6-6fa035707a53.png)

**Comment by wind39** [comment]
Hi @erdusa ,

I managed to fix this issue in [this commit](https://github.com/OmniDB/OmniDB/commit/fe1e603c08e375a78d86e98a2a4f0ea7415ec392).

It is going to be released in next OmniDB version, 2.15, which is planned for next April.

Best regards,

William

**Comment by wind39** [comment]
Hi @erdusa ,

OmniDB 2.15 is out, containing a fix for this issue.

We are keeping this ticket open for a few more days, in case you want to provide us your valuable feedback, as always.

Best regards,

William

**Comment by erdusa** [comment]
Hi @wind39, I can see this issue was resolved, thanks very much, but I would like to use the new feature "SSH terminal emulator" but I cannot find it. Could you tell me how I can use that, by email, thanks

**Comment by rafaelthca** [comment]
hi @erdusa,

If you open the connection grid, you'll find a new technology called `terminal`. Use it to configure a connection to a SSH terminal. You can open the tab from there, clicking in the action button.

Additionally, you can also open already configured SSH terminals by clicking in the `+` tab, in the connections tab interface:

![image](https://user-images.githubusercontent.com/9335851/56520065-ec9fe380-6519-11e9-9b55-06dc221a365c.png)

Database connections that have SSH tunnel configured will also appear in that list.

Let me know if that works for you.

**Comment by erdusa** [comment]
Hi @rafaelthca, thanks you for your answer this new feature is very good.

Casually I saw a message in the postgresql log when I open the monitoring tab 

![image](https://user-images.githubusercontent.com/36895220/56522121-b5c2d100-650b-11e9-91ba-5ded0f77d5de.png)

**Comment by df7cb** [comment]
Fwiw, the problem with timestamptz primary keys is still present in 2.16.0:

```
Command: update public.log set qsltx = 'R' where to_char(start = '2019-06-16 17:29:00'::timestamp, 'YYYY-mm-dd hh24:mi:ss') and call = 'JR4GPA'

Message:

function to_char(boolean, unknown) does not exist
LINE 1: update public.log set qsltx = 'R' where to_char(start = '201...
                                                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```
Please reopen this issue.

**Comment by barthisrael** [comment]
Hi @df7cb ,

Please check it against OmniDB 3.0. It's supposed to be fixed in that version.

Regards.

**Comment by df7cb** [comment]
It finally got to update the Debian package, and also checked that timestamptz columns in PK finally work. Thanks!
