### ISSUE TITLE
Traceback in export process

### ISSUE THREAD

**Issue by ChrisForsythe** [OmniDB/OmniDB#519]
When attempting to export, my local installation on windows 10 of the 64 bit binary of 2.7.0 gives this:

```
Traceback (most recent call last):
  File "OmniDB\ws_core.py", line 213, in thread_dispatcher
KeyError: 'conn_tabs_tab6'
```

How I produced this:

 

1. Run query
2. Password prompt for authentication
3. 50 rows returned
4. Export with csv option.
5. Click save. Note it is html (it actually saves the interface for omnidb and not the data).
6. Cancel
7. Click anywhere and you get this exception.

**Comment by rafaelthca** [comment]
Hi @ChrisForsythe,

Thanks for filling this issue. Are you using app or server?

Do you always get the same issue when performing those steps or was it a one time issue? Also, are you able to perform queries in the same query tab or in other query tabs that belong to the same connection tab?

Rafael.

**Comment by ChrisForsythe** [comment]
1. The app.
2. It's very repeatable.
3. Once the traceback is shown the interface will not continue executing queries, regardless of which tab.

**Comment by ChrisForsythe** [comment]
I think I did try exporting to xlsx at some point right before this all started.

**Comment by rafaelthca** [comment]
Ok. When you say that it is very repeatable, you are unable to use the export feature at all or does it happen in specific situations?

**Comment by davidemorano** [comment]
Hi, same error reported by @ChrisForsythe, but on Ubuntu 16.04.
Regards,
Davide

**Comment by ChrisForsythe** [comment]
Unable to use it at all, any attempt is a continued traceback being thrown.

**Comment by rafaelthca** [comment]
Thanks guys, trying again to simulate here.

@davidemorano, can you outline the steps you perform since OmniDB is started? I am referring to actions in the interface, such as, creating a new connection tab, selecting a different connection, performing a query, providing password, etc.

**Comment by davidemorano** [comment]
Hi,
1. open omnidb
2. open an exiting connection
3. run a query
4. click "export data" with CSV already set
5. then click "Save"
6. re-run the same query and the error occurred.

If I close omnidb and re-run the same steps above, sometimes go right, no error occurred... So I cannot replicate the error always on my laptop...

**Comment by rafaelthca** [comment]
Ok, was finally able to simulate it.

Here is what is happening. Every time OmniDB is started and its main page is loaded it wipes a dictionary containing all connection objects.

You are seeing this error because you are exporting something that is generating an exception. The bug here is that OmniDB tries to download an empty link (because there is no file) and ends up loading the main page again and wiping that dictionary. As a result no other operation can be performed in the current window.

I already fixed this, to show the exception instead of trying to download an empty file. But I still don't know why the exception was generated in the first place. @ChrisForsythe can you tell me what kind of data are you trying to export?

**Comment by wind39** [comment]
Hi @ChrisForsythe ,

Kindly checking if, with latest release, you are still facing the same issue.

Thanks and regards,
William Ivanski

**Comment by wind39** [comment]
As it is fixed, I'm closing this issue now.
