### ISSUE TITLE
Running SQL-Scripts

### ISSUE THREAD

**Issue by manuelfrei** [OmniDB/OmniDB#694]
Is there a Way to run multiple SQL statements in one tab? Will this restriction be resolved at some point?
Thankyou for your work!

**Comment by wind39** [comment]
Hi @manuelfrei ,

Since you opened this issue, OmniDB received lots of improvements to the Query Tab. Particularly, now it is possible to run multiple SQL statements in a single Query Tab and you also have transaction control.

Last week we released version 2.14. Would you please try it and provide us with your feedback?

Thanks in advance,

William

**Comment by wind39** [comment]
Closing this.

**Comment by Prakkie** [comment]
Hi,

I am trying to run multiple queries in OmniDB v2.16 on Oracle DB and I get error: ORA-00933: SQL command not properly ended.

I am just trying 
select * from tab;
select * from tab;

I have also tried DDLs. I tried selecting all queries and clicking on Run. No luck.
Please advise if I am missing something.

Thanks.

**Comment by jdelramirez** [comment]
How is going this, still getting the same bug,
thanks!

**Comment by peterpanmj** [comment]
select 1 from dual;
select 1 from dual;
click run
ORA-00911: invalid character

I am using v2.17. It is not solved for Oracle.
