### ISSUE TITLE
Edit data doesn't work with timestamptz primary key

### ISSUE THREAD

**Issue by df7cb** [OmniDB/OmniDB#907]
I have a table with a PK on (timestamptz, text). Editing data results in a update query like this:
```
2019-04-05 20:36:16.689 GMT [5098] myon@cb ERROR:  function to_char(boolean, unknown) does not exist at character 43
2019-04-05 20:36:16.689 GMT [5098] myon@cb HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2019-04-05 20:36:16.689 GMT [5098] myon@cb STATEMENT:  update public.log set name = 'test' where to_char(start = '2019-04-02 06:36:15'::timestamp, 'YYYY-mm-dd hh24:mi:ss') and call = 'IG9MO'
```
Apparently it is trying to apply the timestamptz output formatting for the UPDATE as well.

Also, why is the error message not cut-and-paste-able?

**Comment by wind39** [comment]
Hi @ChristophBerg ,

Thanks for reaching out.

This is a duplicate of #439 , and this was already fixed. The fix will reach master branch and will be released on 2.15 next week (April, 11).

We will also tackle the error message popup so users will be able to send the text to the clipboard.

I will let you know when we have any news via this ticket.

Regards,

William

**Comment by wind39** [comment]
Hi @df7cb ,

We just released OmniDB 2.15 with a fix for both issues. The fixed code can also be found in `master` branch now.

Keeping this open for a few days in case you want to provide some feedback.

Thanks and regards,

William

**Comment by wind39** [comment]
Closing this now.

**Comment by omaximenco** [comment]
Not sure what was fixed, but the problem is still there (v2.17.0):
function to_char(boolean, unknown) does not exist
PK is a date field + a varchar field.

**Comment by df7cb** [comment]
That's indeed still broken even in 2.17.0. The `start =` part is still inside to_char().
```
function to_char(boolean, unknown) does not exist
LINE 1: update public.log set qth = 'test' where to_char(start = '20...
```
